// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Collection struct {
	ID            string
	Name          string
	Dimension     sql.NullInt64
	DatabaseID    string
	ConfigJsonStr sql.NullString
}

type CollectionMetadatum struct {
	CollectionID sql.NullString
	Key          string
	StrValue     sql.NullString
	IntValue     sql.NullInt64
	FloatValue   sql.NullFloat64
	BoolValue    sql.NullInt64
}

type Database struct {
	ID       string
	Name     string
	TenantID string
}

type Embedding struct {
	ID          int64
	SegmentID   string
	EmbeddingID string
	SeqID       []byte
	CreatedAt   time.Time
}

type EmbeddingFulltextSearch struct {
	StringValue string
}

type EmbeddingMetadatum struct {
	ID          sql.NullInt64
	Key         string
	StringValue sql.NullString
	IntValue    sql.NullInt64
	FloatValue  sql.NullFloat64
	BoolValue   sql.NullInt64
}

type EmbeddingsQueue struct {
	SeqID     int64
	CreatedAt time.Time
	Operation int64
	Topic     string
	ID        string
	Vector    []byte
	Encoding  sql.NullString
	Metadata  sql.NullString
}

type EmbeddingsQueueConfig struct {
	ID            int64
	ConfigJsonStr sql.NullString
}

type MaintenanceLog struct {
	ID        int64
	Timestamp int64
	Operation string
}

type MaxSeqID struct {
	SegmentID string
	SeqID     []byte
}

type Segment struct {
	ID         string
	Type       string
	Scope      string
	Collection string
}

type SegmentMetadatum struct {
	SegmentID  sql.NullString
	Key        string
	StrValue   sql.NullString
	IntValue   sql.NullInt64
	FloatValue sql.NullFloat64
	BoolValue  sql.NullInt64
}

type Tenant struct {
	ID string
}
