name: Go Test

on:
  workflow_call: { }
  workflow_dispatch: { }
  pull_request:
    paths:
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
      - main.go
jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/go-lint.yaml
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    needs: [ lint ]
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ] #, windows-latest, macos-latest, macos-14, ubuntu-latest,
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Build and Test
        run: |
          make go-test
